### ISSUE TITLE
Can't build on OSX - Makefile

### ISSUE THREAD

**Issue by satchm0h** [chxdeng/mabain#12]
Because OSX (w/ default HFS+ settings) does not enforce case sensitivity in the filesystem, the `BUILD` file ends up matching the `build` target in the Makefile and you always get:

`> make build`
`make: 'build' is up to date.`

If you rename the BUILD file it actually builds (see another issue I'm about to open there)

Attached: potentially useful version info
[typescript.txt](https://github.com/chxdeng/mabain/files/1857637/typescript.txt)

**Comment by chxdeng** [comment]
This issue was fixed by removing the BUILD file.
