### ISSUE TITLE
Can't build on OSX - Compilation errors

### ISSUE THREAD

**Issue by satchm0h** [chxdeng/mabain#13]
I know you don't claim support for OSX, but I thought I would capture the output of the compilation errors anyway. Note, I've hit some of the same errors attempting to build within an alpine Linux Docker container. Maybe it's just a C++ version dependency? If so, maybe just call out that dependency in the README and close this Issue as resolved.

Attached: Potentially useful software versions, Compiler Errors.

[sw_versions.txt](https://github.com/chxdeng/mabain/files/1857673/sw_versions.txt)
[compile_errors.txt](https://github.com/chxdeng/mabain/files/1857674/compile_errors.txt)

**Comment by chxdeng** [comment]
Thanks for reporting. Will fix these issues.
