### ISSUE TITLE
Add support of macOS systems

### ISSUE THREAD

**Issue by Alkenso** [chxdeng/mabain#45]
I've found that build misses support of macOS build out-of-the-box.
Let's add macOS support, it requires quiet few changes, at least for build of the library itself.

**Comment by chxdeng** [comment]
Just to confirm, do you use xcode for compilation?
Thanks

**Comment by Alkenso** [comment]
Thanks for reply,

Usually I prefer to use commandline build via make/cmake

**Comment by chxdeng** [comment]
This should have been resolved.
